### ISSUE TITLE
Unrecognized field "updateTime"

### ISSUE THREAD

**Issue by kernelogic** [binance-exchange/binance-java-api#2]
Exception in thread "main" com.binance.api.client.exception.BinanceApiException: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "updateTime" (class com.binance.api.client.domain.account.Account), not marked as ignorable (8 known properties: "canTrade", "takerCommission", "balances", "sellerCommission", "buyerCommission", "makerCommission", "canWithdraw", "canDeposit"])
 at [Source: okhttp3.ResponseBody$BomAwareReader@7722c3c3; line: 1, column: 164] (through reference chain: com.binance.api.client.domain.account.Account["updateTime"])
	at com.binance.api.client.impl.BinanceApiServiceGenerator.executeSync(BinanceApiServiceGenerator.java:60)
	at com.binance.api.client.impl.BinanceApiRestClientImpl.getAccount(BinanceApiRestClientImpl.java:139)
	at com.binance.api.client.impl.BinanceApiRestClientImpl.getAccount(BinanceApiRestClientImpl.java:144)

**Comment by bigcong** [comment]
需要在Account.java 加入updateTime属性，然后生成get和set方法

**Comment by joaopsilva** [comment]
Hello,

There was a new property added to the Binance API, which was not reflected in the code; this is now fixed.

Please update your code to the latest version, and it should work fine.

Best regards,
João

**Comment by MickeySaeys** [comment]
Hello,

I'm still having this issue while I downloaded the latest version on Github.

Best regards,
Mickey
