### ISSUE TITLE
rectWindow must be less than 60000

### ISSUE THREAD

**Issue by mylastwanto** [binance-exchange/binance-java-api#221]
According [Binance API CHANGELOG (2019-08-15)](https://github.com/binance-exchange/binance-official-api-docs/blob/master/CHANGELOG.md) , recvWindow cannot exceed 60000 or will throw error (-1131 BAD_RECV_WINDOW)

So BinanceApiConstants.DEFAULT_RECEIVING_WINDOW should set to max 60000L

**Solution temporary before change :**

NewOrder newOrder = NewOrder.marketBuy("BTCUSDT", amount);
newOrder.recvWindow(5000L);
        
NewOrderResponse newOrderResponse = client.newOrder(newOrder);

**Comment by net968** [comment]
Change to 

 public static final long DEFAULT_RECEIVING_WINDOW = 5_000L;

**Comment by mlaubre** [comment]
Not a solution for binanceApiService.getAccount() which gives "Timestamp for this request is outside of the recvWindow"

**Comment by mcourteaux** [comment]
> Not a solution for binanceApiService.getAccount() which gives "Timestamp for this request is outside of the recvWindow"

Check your systems clock. System.currenTimeMillis() gives milliseconds since epoch, which is independent of timezone.

**Comment by soleetions** [comment]
Same issue here.
Since the Binance rest api upgrade my client is failing as well.
Changed BinanceApiConstants.DEFAULT_RECEIVING_WINDOW to 60_000L and it's working again

**Comment by antonvalletas** [comment]
Please merge this @joaopsilva

**Comment by joaopsilva** [comment]
This is now fixed.

**Comment by Sclipse** [comment]
I'm still getting an exception "Exception in thread "main" com.binance.api.client.exception.BinanceApiException: 'recvWindow' must be less than 60000."

**Comment by xXSkyWalkerXx1** [comment]
I still have this issue. :D
